id: ce6cbbcb3a75431f95bf72cf619d0a05
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_308-Questions%20Regarding%20Death%20and%20Transmigration-v2
  language: en
  author: ''
  volume: {}
